version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      patch:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "patch"
      minor-and-patch:
        applies-to: security-updates
        patterns:
        - "*"
        update-types:
        - "patch"
        - "minor"